name: Task
description: Track a discrete task
labels: [task]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
    validations:
      required: true
  - type: input
    id: milestone
    attributes:
      label: Milestone
      placeholder: M0-M5
